export const fonts = () => [
  "Alpino",
  "Amulya",
  "Archivo",
  "Asap",
  "Author",
  "Azeret Mono",
  "Bespoke Sans",
  "Bespoke Serif",
  "Bespoke Slab",
  "Bespoke Stencil",
  "Bevellier",
  "Bonny",
  "Boska",
  "Britney",
  "Chillax",
  "Chubbo",
  "Clash Display",
  "Clash Grotesk",
  "Crimson Pro",
  "Dancing Script",
  "Epilogue",
  "Erode",
  "Excon",
  "Expose",
  "Familjen Grotesk",
  "Fira Sans",
  "Gambarino",
  "Gambetta",
  "General Sans",
  "Hind",
  "Hoover",
  "Kalam",
  "Karma",
  "Khand",
  "Kohinoor Zerone",
  "Literata",
  "Lora",
  "Manrope",
  "Melodrama",
  "Merriweather",
  "Montserrat",
  "Neco",
  "New Title",
  "Nippo",
  "Nunito",
  "Oswald",
  "Outfit",
  "Pally",
  "Panchang",
  "Paquito",
  "Pilcrow Rounded",
  "Plein",
  "Plus Jakarta Sans",
  "Poppins",
  "Pramukh Rounded",
  "Public Sans",
  "Quicksand",
  "Quilon",
  "Rajdhani",
  "Ranade",
  "Recia",
  "Red Hat Display",
  "Roundo",
  "Rowan",
  "Satoshi",
  "Sentient",
  "Sharpie",
  "Sora",
  "Space Grotesk",
  "Spline Sans",
  "Styro",
  "Supreme",
  "Switzer",
  "Synonym",
  "Tabular",
  "Technor",
  "Teko",
  "Telma",
  "Trench Slab",
  "Work Sans",
  "Zodiak",
];
